sizes    = (                'xs',   's',    'm',    'ml',   'l',    'xl')
geometry = {
    'seat tube length':     (410,   445,    480,    515,    535,    565),
    'seat tube angle':      (74.5,  74,     73.5,   73,     73,     72.5),
    'top tube length':      (510,   530,    545,    560,    575,    595),
    'head tube length':     (125,   145,    165,    190,    210,    230),
    'head tube angle':      (71,    72,     72.5,   72.5,   72.5,   72.5),
    'fork rake':            (45,    45,     45,     45,     45,     45),
    'trail':                (70,    64,     60,     60,     60,     60),
    'wheelbase':            (983,   990,    995,    1007,   1022,   1037),
    'chain stay length':    (420,   420,    420,    420,    420,    420),
    'bottom bracket drop':  (70,    70,     70,     65,     65,     65),
    'stack':                (523,   546,    567,    586,    605,    624),
    'reach':                (365,   373,    377,    381,    390,    398),
    'stand over height':    (737,   754,    777,    790,    813,    833),
    'handlebar width':      (400,   400,    420,    420,    440,    440),
    'stem length':          (80,    90,     100,    110,    110,    120),
    'crank length':         (170,   170,    172.5,  172.5,  175,    175),
}
